### ISSUE TITLE
integration fails to setup

### ISSUE THREAD

**Issue by talex-05** [jaredhobbs/home-assistant-hx3#4]
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry hx3 for hx3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hx3/__init__.py", line 65, in async_setup_entry
    hass.config_entries.async_setup_platforms(config, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

FIX:
/config/custom_components/hx3/__init__.py  edit line 65:

await hass.config_entries.async_forward_entry_setups(config, PLATFORMS)

**Comment by brandroidian** [comment]
+1
Mine has stopped working. I'm used to having to reset mine every couple months, but it will no longer complete the configuration
/ # @
[error_log-1.txt](https://github.com/jaredhobbs/home-assistant-hx3/files/11468637/error_log-1.txt)

**Comment by jaredhobbs** [comment]
the hx3 api changed providers. sorry for the delay!
