### ISSUE TITLE
Can't connect to service after rebooting HA after a couple of days

### ISSUE THREAD

**Issue by lwalkera** [jaredhobbs/home-assistant-hx3#5]
## Version of the custom_component
Latest AFAIK.

## Describe the bug
Integration is unable to get a new token if HA is rebooted. Token may have expired. Would be nice to use the same auth interface the main app uses instead of the janky sharing API.

## Debug log
Logger: homeassistant.config_entries
Source: custom_components/hx3/__init__.py:89
Integration: Hx 3 Thermostat ([documentation](https://github.com/jaredhobbs/home-assistant-hx3), [issues](https://github.com/jaredhobbs/home-assistant-hx3/issues))
First occurred: May 29, 2023 at 19:28:12 (1 occurrences)
Last logged: May 29, 2023 at 19:28:12

Error setting up entry hx3 for hx3
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 621, in _execute
    ret = self._client.execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Context creation failed: Token expired', 'extensions': {'code': 'UNAUTHENTICATED'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 621, in _execute
    ret = self._client.execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Context creation failed: Token expired', 'extensions': {'code': 'UNAUTHENTICATED'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 621, in _execute
    ret = self._client.execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Context creation failed: Token expired', 'extensions': {'code': 'UNAUTHENTICATED'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 621, in _execute
    ret = self._client.execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Context creation failed: Token expired', 'extensions': {'code': 'UNAUTHENTICATED'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 621, in _execute
    ret = self._client.execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Context creation failed: Token expired', 'extensions': {'code': 'UNAUTHENTICATED'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/hx3/__init__.py", line 28, in async_setup_entry
    client = await hass.async_add_executor_job(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/hx3/__init__.py", line 89, in get_hx3_client
    return api.Hx3Api(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 601, in __init__
    self._get_new_token()
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 693, in _get_new_token
    result = self._execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 630, in _execute
    self._authenticate()
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 655, in _authenticate
    result = self._execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 630, in _execute
    self._authenticate()
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 655, in _authenticate
    result = self._execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 630, in _execute
    self._authenticate()
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 655, in _authenticate
    result = self._execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 630, in _execute
    self._authenticate()
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 655, in _authenticate
    result = self._execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 630, in _execute
    self._authenticate()
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 655, in _authenticate
    result = self._execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 633, in _execute
    raise e
  File "/srv/homeassistant/lib/python3.9/site-packages/hx3/api.py", line 621, in _execute
    ret = self._client.execute(
  File "/srv/homeassistant/lib/python3.9/site-packages/gql/client.py", line 78, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Context creation failed: Token expired', 'extensions': {'code': 'UNAUTHENTICATED'}}

```

**Comment by jaredhobbs** [comment]
the hx3 api changed providers. sorry for the delay!
